scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: carter_body_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        min_x: -0.60
        max_x: 0.60
        min_y: -0.40
        max_y: 0.40
        min_z: -0.15
        max_z: 0.80
        invert: false
